name: Tokamak Optimism Public (Release Version)

on:
  push:
    tags:
      - 'release-*'

jobs:
  go-packages:
    name: Publish Go Packages
    strategy:
      matrix:
        package:
          [
            l2geth,
            batch-submitter,
            proxyd,
            gas-oracle,
            indexer,
            op-exporter,
            l2geth-exporter,
            teleportr,
          ]
    runs-on: ubuntu-latest
    outputs:
      newRelease: ${{ steps.extractver.outputs.RELEASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: extractver
        run: |
          echo "RELEASE"=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT
          echo "VERSION=$(jq -r .version ./${{ matrix.package }}/package.json)" >> $GITHUB_OUTPUT
          echo "GITDATE=$(date +%d-%m-%Y)" >> $GITHUB_OUTPUT
          echo "GITSHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.package }}/Dockerfile
          push: true
          provenance: false
          tags: |
            tokamaknetwork/titan-${{ matrix.package }}:${{ steps.extractver.outputs.RELEASE }}
            tokamaknetwork/titan-${{ matrix.package }}:${{ steps.extractver.outputs.VERSION }}
            tokamaknetwork/titan-${{ matrix.package }}:${{ steps.extractver.outputs.GITSHA }}
          build-args: |
            GITDATE=${{ steps.extractver.outputs.GITDATE }}
            GITCOMMIT=${{ steps.extractver.outputs.GITSHA }}
            GITVERSION=${{ steps.extractver.outputs.VERSION }}

  titan-packages:
    name: Publish Titan Packages
    strategy:
      matrix:
        package: [message-relayer, fault-detector]
    runs-on: ubuntu-latest
    outputs:
      newRelease: ${{ steps.extractver.outputs.RELEASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: extractver
        run: |
          echo "RELEASE"=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT
          echo "VERSION=$(jq -r .version ./packages/tokamak/${{ matrix.package }}/package.json)" >> $GITHUB_OUTPUT
          echo "GITDATE=$(date +%d-%m-%Y)" >> $GITHUB_OUTPUT
          echo "GITSHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish Titan Packages
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ops/docker/Dockerfile.packages
          target: titan-${{ matrix.package }}
          push: true
          provenance: false
          tags: |
            tokamaknetwork/titan-${{ matrix.package }}:${{ steps.extractver.outputs.RELEASE }}
            tokamaknetwork/titan-${{ matrix.package }}:${{ steps.extractver.outputs.VERSION }}
            tokamaknetwork/titan-${{ matrix.package }}:${{ steps.extractver.outputs.GITSHA }}
          build-args: |
            GITDATE=${{ steps.extractver.outputs.GITDATE }}
            GITCOMMIT=${{ steps.extractver.outputs.GITSHA }}
            GITVERSION=${{ steps.extractver.outputs.VERSION }}

  data-transport-layer:
    name: Publish Data Transport Layer
    runs-on: ubuntu-latest
    outputs:
      newRelease: ${{ steps.extractver.outputs.RELEASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: extractver
        run: |
          echo "RELEASE"=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT
          echo "VERSION=$(jq -r .version ./packages/data-transport-layer/package.json)" >> $GITHUB_OUTPUT
          echo "GITDATE=$(date +%d-%m-%Y)" >> $GITHUB_OUTPUT
          echo "GITSHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish Data Transport Layer
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ops/docker/Dockerfile.packages
          target: data-transport-layer
          push: true
          provenance: false
          tags: |
            tokamaknetwork/titan-data-transport-layer:${{ steps.extractver.outputs.RELEASE }}
            tokamaknetwork/titan-data-transport-layer:${{ steps.extractver.outputs.VERSION }}
            tokamaknetwork/titan-data-transport-layer:${{ steps.extractver.outputs.GITSHA }}
          build-args: |
            GITDATE=${{ steps.extractver.outputs.GITDATE }}
            GITCOMMIT=${{ steps.extractver.outputs.GITSHA }}
            GITVERSION=${{ steps.extractver.outputs.VERSION }}

  deployer:
    name: Publish Deployer
    runs-on: ubuntu-latest
    outputs:
      newRelease: ${{ steps.extractver.outputs.RELEASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: extractver
        run: |
          echo "RELEASE"=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT
          echo "VERSION=$(jq -r .version ./packages/tokamak/contracts/package.json)" >> $GITHUB_OUTPUT
          echo "GITDATE=$(date +%d-%m-%Y)" >> $GITHUB_OUTPUT
          echo "GITSHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish Deployer
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ops/docker/Dockerfile.packages
          target: titan-deployer
          push: true
          provenance: false
          tags: |
            tokamaknetwork/titan-deployer:${{ steps.extractver.outputs.RELEASE }}
            tokamaknetwork/titan-deployer:${{ steps.extractver.outputs.VERSION }}
            tokamaknetwork/titan-deployer:${{ steps.extractver.outputs.GITSHA }}
          build-args: |
            GITDATE=${{ steps.extractver.outputs.GITDATE }}
            GITCOMMIT=${{ steps.extractver.outputs.GITSHA }}
            GITVERSION=${{ steps.extractver.outputs.VERSION }}

  update-kustomize:
    name: Update image version in kustomize manifest file
    needs:
      - go-packages
      - titan-packages
      - data-transport-layer
      - deployer
    runs-on: ubuntu-latest

    steps:
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: tokamak-network/tokamak-infra
          ref: main
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          path: tokamak-infra

      - name: Update l2geth Kubernetes resources
        run: |
          cd tokamak-infra/tokamak-optimism/kustomize/overlays/aws/mainnet
          kustomize edit set image tokamaknetwork/titan-l2geth:${{ needs.go-packages.outputs.newRelease }}

      - name: Update titan-message-relayer Kubernetes resources
        run: |
          cd tokamak-infra/tokamak-optimism/kustomize/overlays/aws/mainnet
          kustomize edit set image tokamaknetwork/titan-message-relayer:${{ needs.titan-packages.outputs.newRelease }}

      - name: Update data-transport-layer Kubernetes resources
        run: |
          cd tokamak-infra/tokamak-optimism/kustomize/overlays/aws/mainnet
          kustomize edit set image tokamaknetwork/titan-data-transport-layer:${{ needs.data-transport-layer.outputs.newRelease }}

      - name: Update batch-submitter Kubernetes resources
        run: |
          cd tokamak-infra/tokamak-optimism/kustomize/overlays/aws/mainnet
          kustomize edit set image tokamaknetwork/titan-batch-submitter:${{ needs.go-packages.outputs.newRelease }}

      - name: Update proxyd Kubernetes resources
        run: |
          cd tokamak-infra/tokamak-optimism/kustomize/overlays/aws/mainnet
          kustomize edit set image tokamaknetwork/titan-proxyd:${{ needs.go-packages.outputs.newRelease }}

      - name: Update gas-oracle Kubernetes resources
        run: |
          cd tokamak-infra/tokamak-optimism/kustomize/overlays/aws/mainnet
          kustomize edit set image tokamaknetwork/titan-gas-oracle:${{ needs.go-packages.outputs.newRelease }}

      - name: Show updated Kubernetes resources
        run: |
          cd tokamak-infra/tokamak-optimism/kustomize/overlays/aws/mainnet
          cat kustomization.yaml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          github_token: ${{ secrets.BOT_ACCESS_TOKEN }}
          message: '[AUTO] Update tokamak-optimism images tag to ${{ needs.go-packages.outputs.newRelease }} for release'
          cwd: 'tokamak-infra/'
